#!/usr/bin/env bash
# Generates .env.local with secure dev defaults. Idempotent: never overwrites
# an existing file. Invoked by infra/dev.sh on first run.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

if [[ -f .env.local ]]; then
  echo "→ .env.local already exists — leaving it untouched"
  exit 0
fi

# 32+ char random secret for Better Auth.
SECRET="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p | tr -d '\n')"

cat > .env.local <<ENV
# Generated by infra/bootstrap-env.sh — safe to edit. Gitignored.

# Postgres (matches infra/docker-compose.dev.yml)
POSTGRES_USER=northbeam
POSTGRES_PASSWORD=northbeam
POSTGRES_DB=northbeam
DATABASE_URL=postgresql://northbeam:northbeam@localhost:5432/northbeam

# Better Auth
BETTER_AUTH_SECRET=${SECRET}
BETTER_AUTH_URL=http://localhost:8000
PUBLIC_WEB_URL=http://localhost:3000

# Web → API (client). Defaults to :8000 if unset.
NEXT_PUBLIC_API_URL=http://localhost:8000
ENV

echo "→ wrote .env.local (BETTER_AUTH_SECRET generated)"
