/* studio-data.js — mock CRM metadata powering the Studio prototype */
(() => {
  // ---- objects ----
  var OBJECTS = [
    {
      id: 'account',
      name: 'Account',
      plural: 'Accounts',
      api: 'Account',
      icon: 'buildings',
      color: '#635bff',
      source: 'salesforce',
      records: 318,
      fields: 24,
      health: 'good',
      updated: '2d ago',
      desc: 'Companies you sell to and partner with.',
    },
    {
      id: 'contact',
      name: 'Contact',
      plural: 'Contacts',
      api: 'Contact',
      icon: 'user',
      color: '#0ea5e9',
      source: 'salesforce',
      records: 2412,
      fields: 31,
      health: 'good',
      updated: '4h ago',
      desc: 'People at your accounts.',
    },
    {
      id: 'deal',
      name: 'Deal',
      plural: 'Deals',
      api: 'Opportunity',
      icon: 'currency-circle-dollar',
      color: '#10b981',
      source: 'salesforce',
      records: 47,
      fields: 28,
      health: 'warn',
      updated: '12m ago',
      desc: 'Revenue opportunities moving through your pipeline.',
    },
    {
      id: 'lead',
      name: 'Lead',
      plural: 'Leads',
      api: 'Lead',
      icon: 'user-focus',
      color: '#f59e0b',
      source: 'salesforce',
      records: 1203,
      fields: 19,
      health: 'good',
      updated: '1h ago',
      desc: 'Unqualified prospects not yet converted.',
    },
    {
      id: 'activity',
      name: 'Activity',
      plural: 'Activities',
      api: 'Task',
      icon: 'lightning',
      color: '#8b5cf6',
      source: 'salesforce',
      records: 8904,
      fields: 12,
      health: 'good',
      updated: '2m ago',
      desc: 'Calls, emails, and meetings logged against records.',
    },
    {
      id: 'product',
      name: 'Product',
      plural: 'Products',
      api: 'Product2',
      icon: 'package',
      color: '#ec4899',
      source: 'salesforce',
      records: 156,
      fields: 14,
      health: 'good',
      updated: '1w ago',
      desc: 'Your catalog of sellable items.',
    },
    {
      id: 'quote',
      name: 'Quote',
      plural: 'Quotes',
      api: 'Quote',
      icon: 'receipt',
      color: '#14b8a6',
      source: 'salesforce',
      records: 89,
      fields: 17,
      health: 'warn',
      updated: '3d ago',
      desc: 'Pricing proposals tied to deals.',
    },
    {
      id: 'case',
      name: 'Case',
      plural: 'Cases',
      api: 'Case',
      icon: 'lifebuoy',
      color: '#ef4444',
      source: 'salesforce',
      records: 421,
      fields: 22,
      health: 'good',
      updated: '20m ago',
      desc: 'Support tickets and customer issues.',
    },
    {
      id: 'renewal',
      name: 'Renewal',
      plural: 'Renewals',
      api: 'Renewal__c',
      icon: 'arrows-clockwise',
      color: '#3d5afe',
      source: 'native',
      records: 47,
      fields: 9,
      health: 'good',
      updated: '5h ago',
      desc: 'Subscription renewal tracking — built natively.',
    },
    {
      id: 'health',
      name: 'Health Score',
      plural: 'Health Scores',
      api: 'HealthScore__ai',
      icon: 'heartbeat',
      color: '#a855f7',
      source: 'ai',
      records: 318,
      fields: 6,
      health: 'good',
      updated: 'live',
      desc: 'AI-derived account health, recomputed continuously.',
    },
    {
      id: 'onboarding',
      name: 'Onboarding',
      plural: 'Onboardings',
      api: 'Onboarding__c',
      icon: 'clipboard-text',
      color: '#0891b2',
      source: 'native',
      records: 31,
      fields: 11,
      health: 'good',
      updated: '6h ago',
      desc: 'Post-sale onboarding projects.',
    },
  ];

  // ---- field type catalog ----
  var FIELD_TYPES = [
    {
      id: 'text',
      label: 'Text',
      icon: 'text-t',
      group: 'Basic',
      desc: 'Single line up to 255 chars',
    },
    {
      id: 'longtext',
      label: 'Long text',
      icon: 'text-align-left',
      group: 'Basic',
      desc: 'Multi-line paragraph',
    },
    {
      id: 'richtext',
      label: 'Rich text',
      icon: 'text-aa',
      group: 'Basic',
      desc: 'Formatted text & links',
    },
    {
      id: 'checkbox',
      label: 'Checkbox',
      icon: 'check-square',
      group: 'Basic',
      desc: 'True / false',
    },
    { id: 'number', label: 'Number', icon: 'hash', group: 'Numbers', desc: 'Integer or decimal' },
    {
      id: 'currency',
      label: 'Currency',
      icon: 'currency-dollar',
      group: 'Numbers',
      desc: 'Money with currency code',
    },
    {
      id: 'percent',
      label: 'Percent',
      icon: 'percent',
      group: 'Numbers',
      desc: 'Percentage value',
    },
    {
      id: 'date',
      label: 'Date',
      icon: 'calendar-blank',
      group: 'Date & time',
      desc: 'Calendar date',
    },
    {
      id: 'datetime',
      label: 'Date / time',
      icon: 'clock',
      group: 'Date & time',
      desc: 'Date with timestamp',
    },
    {
      id: 'picklist',
      label: 'Picklist',
      icon: 'list-checks',
      group: 'Choice',
      desc: 'Single choice from a set',
    },
    {
      id: 'multipicklist',
      label: 'Multi-select',
      icon: 'list-plus',
      group: 'Choice',
      desc: 'Multiple choices',
    },
    {
      id: 'email',
      label: 'Email',
      icon: 'envelope-simple',
      group: 'Contact',
      desc: 'Validated email address',
    },
    {
      id: 'phone',
      label: 'Phone',
      icon: 'phone',
      group: 'Contact',
      desc: 'Formatted phone number',
    },
    { id: 'url', label: 'URL', icon: 'link-simple', group: 'Contact', desc: 'Web address' },
    {
      id: 'lookup',
      label: 'Lookup',
      icon: 'arrow-bend-up-right',
      group: 'Relationship',
      desc: 'Reference another object',
    },
    {
      id: 'masterdetail',
      label: 'Master-detail',
      icon: 'tree-structure',
      group: 'Relationship',
      desc: 'Tight parent-child link',
    },
    {
      id: 'rollup',
      label: 'Rollup',
      icon: 'sigma',
      group: 'Relationship',
      desc: 'Aggregate child records',
    },
    {
      id: 'formula',
      label: 'Formula',
      icon: 'function',
      group: 'Advanced',
      desc: 'Computed from other fields',
    },
    {
      id: 'autonumber',
      label: 'Auto-number',
      icon: 'list-numbers',
      group: 'Advanced',
      desc: 'Sequential identifier',
    },
    {
      id: 'geo',
      label: 'Geolocation',
      icon: 'map-pin',
      group: 'Advanced',
      desc: 'Latitude / longitude',
    },
    { id: 'file', label: 'File', icon: 'paperclip', group: 'Advanced', desc: 'Attachments' },
    {
      id: 'user',
      label: 'User',
      icon: 'user-circle',
      group: 'Relationship',
      desc: 'Reference a team member',
    },
    {
      id: 'ai',
      label: 'AI field',
      icon: 'sparkle',
      group: 'AI',
      desc: 'Derived by an AI model, continuously',
    },
  ];

  // ---- fields for the Deal object (the detail screen) ----
  var DEAL_FIELDS = [
    {
      id: 'f1',
      label: 'Deal Name',
      api: 'Name',
      type: 'text',
      required: true,
      source: 'salesforce',
      desc: 'Display name of the opportunity',
    },
    {
      id: 'f2',
      label: 'Amount',
      api: 'Amount',
      type: 'currency',
      required: false,
      source: 'salesforce',
      desc: 'Total contract value',
    },
    {
      id: 'f3',
      label: 'Stage',
      api: 'StageName',
      type: 'picklist',
      required: true,
      source: 'salesforce',
      options: ['New', 'Qualified', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost'],
    },
    {
      id: 'f4',
      label: 'Close Date',
      api: 'CloseDate',
      type: 'date',
      required: true,
      source: 'salesforce',
    },
    {
      id: 'f5',
      label: 'Account',
      api: 'AccountId',
      type: 'lookup',
      required: true,
      source: 'salesforce',
      related: 'Account',
    },
    {
      id: 'f6',
      label: 'Primary Contact',
      api: 'ContactId',
      type: 'lookup',
      required: false,
      source: 'salesforce',
      related: 'Contact',
    },
    {
      id: 'f7',
      label: 'Owner',
      api: 'OwnerId',
      type: 'user',
      required: true,
      source: 'salesforce',
    },
    {
      id: 'f8',
      label: 'Probability',
      api: 'Probability',
      type: 'percent',
      required: false,
      source: 'salesforce',
      formula: 'stage-weighted',
    },
    {
      id: 'f9',
      label: 'Lead Source',
      api: 'LeadSource',
      type: 'picklist',
      required: false,
      source: 'salesforce',
      options: ['Inbound', 'Outbound', 'Referral', 'Event', 'Partner'],
    },
    {
      id: 'f10',
      label: 'Forecast Category',
      api: 'ForecastCategory',
      type: 'picklist',
      required: false,
      source: 'salesforce',
      options: ['Pipeline', 'Best Case', 'Commit', 'Closed'],
    },
    {
      id: 'f11',
      label: 'Next Step',
      api: 'NextStep',
      type: 'text',
      required: false,
      source: 'salesforce',
    },
    {
      id: 'f12',
      label: 'Description',
      api: 'Description',
      type: 'longtext',
      required: false,
      source: 'salesforce',
    },
    {
      id: 'f13',
      label: 'Renewal Date',
      api: 'Renewal_Date__c',
      type: 'date',
      required: false,
      source: 'native',
      desc: 'When this contract comes up for renewal',
    },
    {
      id: 'f14',
      label: 'Health Score',
      api: 'Health_Score__ai',
      type: 'ai',
      required: false,
      source: 'ai',
      desc: '0–100 likelihood to close, recomputed hourly',
    },
    {
      id: 'f15',
      label: 'Days in Stage',
      api: 'Days_In_Stage__c',
      type: 'formula',
      required: false,
      source: 'native',
      formula: 'TODAY() − StageEntered',
    },
  ];

  // AI-suggested fields (inline suggestions on the object detail)
  var SUGGESTED_FIELDS = [
    {
      label: 'Competitor',
      type: 'picklist',
      reason: '73% of won/lost notes mention a competitor — capture it structured.',
    },
    {
      label: 'Expansion ARR',
      type: 'currency',
      reason: 'Detected upsell language in 18 deals with no field to track it.',
    },
    {
      label: 'Champion',
      type: 'lookup',
      reason: 'Most deals reference a key contact in notes; link it as a relationship.',
    },
  ];

  // ---- schema relationships ----
  var REL = [
    { from: 'contact', to: 'account', kind: 'lookup', label: 'works at' },
    { from: 'deal', to: 'account', kind: 'masterdetail', label: 'for' },
    { from: 'deal', to: 'contact', kind: 'lookup', label: 'champion' },
    { from: 'quote', to: 'deal', kind: 'masterdetail', label: 'on' },
    { from: 'renewal', to: 'deal', kind: 'lookup', label: 'renews' },
    { from: 'case', to: 'account', kind: 'lookup', label: 'raised by' },
    { from: 'activity', to: 'deal', kind: 'lookup', label: 'logged on' },
    { from: 'health', to: 'account', kind: 'lookup', label: 'scores' },
    { from: 'onboarding', to: 'account', kind: 'lookup', label: 'for' },
    { from: 'quote', to: 'product', kind: 'lookup', label: 'includes' },
  ];
  // hand-laid canvas positions (x,y in canvas px)
  var SCHEMA_POS = {
    account: { x: 470, y: 250 },
    contact: { x: 150, y: 110 },
    deal: { x: 470, y: 470 },
    lead: { x: 150, y: 320 },
    activity: { x: 800, y: 470 },
    product: { x: 800, y: 700 },
    quote: { x: 470, y: 690 },
    case: { x: 110, y: 540 },
    renewal: { x: 800, y: 250 },
    health: { x: 820, y: 60 },
    onboarding: { x: 470, y: 96 },
  };

  // ---- migration mapping (Salesforce -> Northbeam) ----
  var MIGRATION = {
    summary: { objects: 11, fields: 214, records: '14,070', confidence: 96 },
    objects: [
      {
        sf: 'Account',
        to: 'account',
        status: 'mapped',
        conf: 99,
        fields: 24,
        note: 'Direct match',
      },
      {
        sf: 'Contact',
        to: 'contact',
        status: 'mapped',
        conf: 99,
        fields: 31,
        note: 'Direct match',
      },
      {
        sf: 'Opportunity',
        to: 'deal',
        status: 'mapped',
        conf: 97,
        fields: 28,
        note: 'Renamed to “Deal”',
      },
      { sf: 'Lead', to: 'lead', status: 'mapped', conf: 98, fields: 19, note: 'Direct match' },
      {
        sf: 'Task + Event',
        to: 'activity',
        status: 'merged',
        conf: 91,
        fields: 12,
        note: 'Two objects merged into Activity',
      },
      {
        sf: 'Product2',
        to: 'product',
        status: 'mapped',
        conf: 95,
        fields: 14,
        note: 'Direct match',
      },
      { sf: 'Quote', to: 'quote', status: 'mapped', conf: 96, fields: 17, note: 'Direct match' },
      { sf: 'Case', to: 'case', status: 'mapped', conf: 94, fields: 22, note: 'Direct match' },
      {
        sf: 'Contract',
        to: 'renewal',
        status: 'review',
        conf: 72,
        fields: 9,
        note: 'Best match is Renewal — confirm?',
      },
      {
        sf: 'Campaign',
        to: null,
        status: 'skip',
        conf: 0,
        fields: 18,
        note: 'No target — using native Journeys instead',
      },
    ],
    // field-level for Opportunity -> Deal
    fields: [
      { sf: 'Name', to: 'Deal Name', conf: 100, status: 'mapped' },
      { sf: 'Amount', to: 'Amount', conf: 100, status: 'mapped' },
      { sf: 'StageName', to: 'Stage', conf: 99, status: 'mapped' },
      { sf: 'CloseDate', to: 'Close Date', conf: 100, status: 'mapped' },
      { sf: 'AccountId', to: 'Account', conf: 99, status: 'mapped' },
      { sf: 'Probability', to: 'Probability', conf: 96, status: 'mapped' },
      { sf: 'LeadSource', to: 'Lead Source', conf: 94, status: 'mapped' },
      { sf: 'ForecastCategoryName', to: 'Forecast Category', conf: 88, status: 'mapped' },
      { sf: 'IsWon / IsClosed', to: 'Stage (derived)', conf: 70, status: 'review' },
      {
        sf: 'ExpectedRevenue',
        to: '— (compute from Amount × Probability)',
        conf: 64,
        status: 'review',
      },
    ],
  };

  // ---- reports & dashboards ----
  var INSIGHTS = [
    {
      tone: 'danger',
      icon: 'trend-down',
      title: 'Pipeline slipping',
      body: "$1.2M across 8 deals pushed their close date this week — 3× last week's slip rate.",
    },
    {
      tone: 'warning',
      icon: 'warning',
      title: 'Stage stall',
      body: '5 deals have sat in Negotiation 21+ days. Historically these close at 34%.',
    },
    {
      tone: 'success',
      icon: 'trend-up',
      title: 'Win-rate up',
      body: 'Inbound win rate rose to 41% (+9pts QoQ), led by the Vertex and Lumen accounts.',
    },
  ];
  var FORECAST = [
    { m: 'Jan', actual: 0.62, fc: 0.62 },
    { m: 'Feb', actual: 0.71, fc: 0.71 },
    { m: 'Mar', actual: 0.68, fc: 0.68 },
    { m: 'Apr', actual: 0.83, fc: 0.83 },
    { m: 'May', actual: 0.79, fc: 0.79 },
    { m: 'Jun', actual: 0.9, fc: 0.9 },
    { m: 'Jul', actual: null, fc: 0.97 },
    { m: 'Aug', actual: null, fc: 1.08 },
    { m: 'Sep', actual: null, fc: 1.2 },
  ];
  var REPORTS = [
    { name: 'Pipeline by stage', icon: 'funnel', by: 'You', updated: 'Today' },
    { name: 'Win/loss by source', icon: 'chart-pie-slice', by: 'Aisha K.', updated: 'Yesterday' },
    { name: 'Rep leaderboard', icon: 'ranking', by: 'You', updated: '3d ago' },
    { name: 'Renewals at risk', icon: 'warning-octagon', by: 'AI', updated: 'Auto' },
  ];

  window.STUDIO = {
    OBJECTS: OBJECTS,
    FIELD_TYPES: FIELD_TYPES,
    DEAL_FIELDS: DEAL_FIELDS,
    SUGGESTED_FIELDS: SUGGESTED_FIELDS,
    REL: REL,
    SCHEMA_POS: SCHEMA_POS,
    MIGRATION: MIGRATION,
    INSIGHTS: INSIGHTS,
    FORECAST: FORECAST,
    REPORTS: REPORTS,
  };
})();
